chore: reduce testing time

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -8,64 +8,64 @@ jobs:
   # ==========================
   #  PHP Linting (Laravel Pint)
   # ==========================
-  check-php-changes:
-    runs-on: ubuntu-latest
-    outputs:
-      php_changed: ${{ steps.filter.outputs.changes != '[]' }}
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+  # check-php-changes:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     php_changed: ${{ steps.filter.outputs.changes != '[]' }}
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v4
 
-    - name: Detect PHP file changes
-      id: filter
-      uses: dorny/paths-filter@v2
-      with:
-        base: ${{ github.event.before }}
-        filters: |
-          php_changed:
-              - '**/*.php'
-    - name: Show filtered changes
-      run: echo "${{ steps.filter.outputs.changes }}"
+  #   - name: Detect PHP file changes
+  #     id: filter
+  #     uses: dorny/paths-filter@v2
+  #     with:
+  #       base: ${{ github.event.before }}
+  #       filters: |
+  #         php_changed:
+  #             - '**/*.php'
+  #   - name: Show filtered changes
+  #     run: echo "${{ steps.filter.outputs.changes }}"
 
-  laravel-pint:
-    needs: [ check-php-changes ]
-    runs-on: ubuntu-latest
-    if: needs.check-php-changes.outputs.php_changed == 'true'
-    permissions:
-      contents: write
-    strategy:
-      fail-fast: true
-      matrix:
-        php: [ 8.4 ]
+  # laravel-pint:
+  #   needs: [ check-php-changes ]
+  #   runs-on: ubuntu-latest
+  #   if: needs.check-php-changes.outputs.php_changed == 'true'
+  #   permissions:
+  #     contents: write
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       php: [ 8.4 ]
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v4
 
-    - name: Setup PHP
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: ${{ matrix.php }}
-        extensions: json, dom, curl, libxml, mbstring
-        coverage: none
+  #   - name: Setup PHP
+  #     uses: shivammathur/setup-php@v2
+  #     with:
+  #       php-version: ${{ matrix.php }}
+  #       extensions: json, dom, curl, libxml, mbstring
+  #       coverage: none
 
-    - name: Install Pint
-      run: composer global require laravel/pint
+  #   - name: Install Pint
+  #     run: composer global require laravel/pint
 
-    - name: Run Pint
-      run: pint --test || (pint && touch linted)
+  #   - name: Run Pint
+  #     run: pint --test || (pint && touch linted)
 
-    - name: Commit linted files
-      if: success() && hashFiles('linted') != ''
-      uses: stefanzweifel/git-auto-commit-action@v5
-      with:
-        commit_message: 'chore: lint coding style (pint)'
+  #   - name: Commit linted files
+  #     if: success() && hashFiles('linted') != ''
+  #     uses: stefanzweifel/git-auto-commit-action@v5
+  #     with:
+  #       commit_message: 'chore: lint coding style (pint)'
 
   # ==========================
   #  Laravel Tests
   # ==========================
   laravel-tests:
-    needs: [ laravel-pint ]
+    # needs: [ laravel-pint ]
     runs-on: ubuntu-latest
     env:
       DB_CONNECTION: pgsql
@@ -88,8 +88,8 @@ jobs:
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
 
     steps:
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
+    # - name: Set up Node.js
+    #   uses: actions/setup-node@v3
 
     - name: Set up PHP
       uses: shivammathur/setup-php@v2
@@ -106,12 +106,12 @@ jobs:
         key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
         restore-keys: ${{ runner.os }}-composer-
 
-    - name: Cache NPM dependencies
-      uses: actions/cache@v3
-      with:
-        path: ~/.npm
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: ${{ runner.os }}-node-
+    # - name: Cache NPM dependencies
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: ~/.npm
+    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+    #     restore-keys: ${{ runner.os }}-node-
 
     - name: Copy .env
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
@@ -119,8 +119,8 @@ jobs:
     - name: Install Dependencies
       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
 
-    - name: Install node dependencies
-      run: npm ci
+    # - name: Install node dependencies
+    #   run: npm ci
 
     - name: Generate key
       run: php artisan key:generate
@@ -136,19 +136,17 @@ jobs:
       env:
         DB_PORT: 5432
 
-    - name: Execute Frontend tests (Unit and Feature tests) via vitest with coverage
-      run: npm run test:coverage
-      env:
-        NODE_ENV: ci
-        LARAVEL_BYPASS_ENV_CHECK: 1
+    # - name: Execute Frontend tests (Unit and Feature tests) via vitest with coverage
+    #   run: npm run test:coverage
+    #   env:
+    #     NODE_ENV: ci
+    #     LARAVEL_BYPASS_ENV_CHECK: 1
 
-    - name: Build
-      run: npm run build
+    # - name: type check
+    #   run: npm run type-check
 
-    - name: Lint Frontend
-      run: npm run lint
+    # - name: Lint Frontend
+    #   run: npm run lint
 
     - name: Execute tests (Unit and Feature tests) via PHPUnit
-      run: |
-        php artisan test -v
-        echo "Exit Code: $?"
+      run: php artisan test
